name: moabb
channels:
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - aiofiles=22.1.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - colorspacious=1.1.2
  - comm=0.1.2
  - contourpy=1.0.5
  - coverage=7.2.2
  - cryptography=41.0.3
  - curl=8.4.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - darkdetect=0.8.0
  - dask-core=2023.6.0
  - dav1d=1.2.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dipy=1.7.0
  - double-conversion=3.2.0
  - edflib-python=1.0.8
  - eeglabio=0.0.2.post4
  - eigen=3.3.7
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.9.2
  - future=0.18.3
  - gettext=0.21.1
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.78.3
  - glib-tools=2.78.3
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - h5io=0.1.9
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icc_rt=2022.1.0
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.4
  - imageio-ffmpeg=0.4.9
  - importlib-metadata=6.0.0
  - importlib_resources=6.1.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsoncpp=1.9.5
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - kaleido-core=0.1.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.1.2
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=15.0.7
  - libcurl=8.4.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libflang=5.0.0
  - libglib=2.78.3
  - libiconv=1.17
  - libmatio=1.5.23
  - libnetcdf=4.9.1
  - libogg=1.3.5
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-meta=5.0.0
  - llvmlite=0.41.1
  - locket=1.0.0
  - loguru=0.5.3
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - memory_profiler=0.61.0
  - mffpy=0.8.0
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mne=1.6.0
  - mne-base=1.6.0
  - mne-bids=0.13
  - mne-qt-browser=0.6.1
  - more-itertools=8.12.0
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nibabel=5.2.0
  - nilearn=0.10.2
  - nlohmann_json=3.11.2
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numba=0.58.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openh264=2.3.1
  - openjpeg=2.4.0
  - openmeeg=2.5.6
  - openmp=5.0.0
  - openssl=3.0.13
  - packaging=23.1
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.3
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=3.10.0
  - plotly=5.20.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - proj=9.1.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - pybv=0.7.5
  - pycparser=2.21
  - pygments=2.15.1
  - pymatreader=0.0.32
  - pyopengl=3.1.1a1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtgraph=0.13.1
  - pyriemann=0.5
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.4.0
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-kaleido=0.1.0
  - python-picard=0.7
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyvista=0.43.1
  - pyvistaqt=0.11.0
  - pywavelets=1.4.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qt-main=5.15.8
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.11.3
  - scooby=0.9.2
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - svt-av1=1.4.1
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - trame=3.4.0
  - trame-client=2.14.1
  - trame-components=2.2.1
  - trame-deckgl=2.0.2
  - trame-markdown=2.0.2
  - trame-matplotlib=2.0.2
  - trame-plotly=2.1.1
  - trame-rca=0.4.1
  - trame-router=2.1.0
  - trame-server=2.13.1
  - trame-simput=2.3.3
  - trame-vega=2.0.3
  - trame-vtk=2.6.3
  - trame-vuetify=2.3.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucrt=10.0.20348.0
  - urllib3=1.26.18
  - utfcpp=3.2.1
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - vtk=9.2.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.14.1
  - wslink=1.12.4
  - x264=1!164.3095
  - x265=3.5
  - xlrd=2.0.1
  - xmltodict=0.13.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yarl=1.8.1
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - braindecode==0.8.1
      - cachetools==5.3.2
      - docstring-inheritance==2.1.1
      - einops==0.7.0
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - keras==2.15.0
      - libclang==16.0.6
      - markdown==3.5.1
      - ml-dtypes==0.2.0
      - moabb==1.0.0
      - mpmath==1.3.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - skorch==0.15.0
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - torch==2.1.2
      - torchinfo==1.8.0
      - werkzeug==3.0.1
